"""init: 9 tables

Revision ID: 1542269914d5
Revises: 
Create Date: 2026-07-13 23:33:23.823156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1542269914d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='备份文件路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号（唯一标识）'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别'),
    sa.Column('birthday', sa.String(length=20), nullable=True, comment='生日'),
    sa.Column('skin_type', sa.String(length=20), nullable=True, comment='肤质：干性/油性/混合/敏感'),
    sa.Column('tags', sa.String(length=200), nullable=True, comment='标签（逗号分隔）'),
    sa.Column('total_spent', sa.Float(), nullable=True, comment='累计消费金额'),
    sa.Column('points', sa.Integer(), nullable=True, comment='积分'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='商品名称'),
    sa.Column('barcode', sa.String(length=50), nullable=True, comment='条码'),
    sa.Column('spec', sa.String(length=100), nullable=True, comment='规格（如 30ml / 50g）'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='分类'),
    sa.Column('unit', sa.String(length=10), nullable=False, comment='库存单位'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='图片路径'),
    sa.Column('cost_price', sa.Float(), nullable=False, comment='成本价'),
    sa.Column('retail_price', sa.Float(), nullable=False, comment='零售价'),
    sa.Column('wholesale_price', sa.Float(), nullable=True, comment='批发价'),
    sa.Column('safety_stock', sa.Integer(), nullable=True, comment='安全库存阈值'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='供应商名称'),
    sa.Column('contact', sa.String(length=100), nullable=True, comment='联系人'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='电话'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='商品'),
    sa.Column('change_type', sa.String(length=20), nullable=False, comment='变动类型：采购入库/销售出库/采购退货入库/销售退货入库/盘点调整'),
    sa.Column('change_quantity', sa.Integer(), nullable=False, comment='变动数量（正=入，负=出）'),
    sa.Column('after_quantity', sa.Integer(), nullable=False, comment='变动后库存（用于校验审计）'),
    sa.Column('reference_id', sa.Integer(), nullable=True, comment='关联单据ID'),
    sa.Column('reference_type', sa.String(length=50), nullable=True, comment='关联单据类型（purchase_order/sale_order/check）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_log_product_id'), 'inventory_log', ['product_id'], unique=False)
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True, comment='供应商'),
    sa.Column('total_amount', sa.Float(), nullable=False, comment='总金额'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True, comment='关联会员'),
    sa.Column('total_amount', sa.Float(), nullable=False, comment='原价合计'),
    sa.Column('discount', sa.Float(), nullable=True, comment='优惠金额'),
    sa.Column('actual_amount', sa.Float(), nullable=False, comment='实收金额'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='单价'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_order_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='单价'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sale_order_id'], ['sale_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_order_id', sa.Integer(), nullable=False, comment='关联销售单'),
    sa.Column('express_company', sa.String(length=50), nullable=True, comment='快递公司（顺丰/中通/圆通/韵达/邮政/其他）'),
    sa.Column('express_no', sa.String(length=100), nullable=True, comment='快递单号'),
    sa.Column('ship_status', sa.String(length=20), nullable=True, comment='发货状态：未发货/已发货/已签收/已退货'),
    sa.Column('receiver_name', sa.String(length=100), nullable=True, comment='收货人'),
    sa.Column('receiver_phone', sa.String(length=30), nullable=True, comment='收货电话'),
    sa.Column('receiver_address', sa.Text(), nullable=True, comment='收货地址'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sale_order_id'], ['sale_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment')
    op.drop_table('sale_order_item')
    op.drop_table('purchase_order_item')
    op.drop_table('sale_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_inventory_log_product_id'), table_name='inventory_log')
    op.drop_table('inventory_log')
    op.drop_table('supplier')
    op.drop_table('product')
    op.drop_table('member')
    op.drop_table('backup_log')
    # ### end Alembic commands ###
