"""add_current_stock

Revision ID: b95d430ccca5
Revises: 4fb2f8fd702e
Create Date: 2026-07-20 22:46:07.985985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95d430ccca5'
down_revision: Union[str, Sequence[str], None] = '4fb2f8fd702e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('product', sa.Column('current_stock', sa.Integer(), nullable=True, comment='当前库存（冗余字段，由库存日志同步维护）'))
    # 从 inventory_log 回填已有数据
    op.execute("""UPDATE product SET current_stock = COALESCE(
        (SELECT SUM(change_quantity) FROM inventory_log WHERE product_id = product.id), 0
    )""")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'current_stock')
    # ### end Alembic commands ###
